### ISSUE TITLE
"-d" option does not seem to be recursive as expected

### ISSUE THREAD

**Issue by qlemaire** [EricZimmerman/Sum#5]
Hello,

The documentation of `sumecmd` states that `-d` input searches for `*.mdb` files recursively within the input folder : 
```
 d               Directory to recursively process, looking for SystemIdentity.mdb, Current.mdb, etc. Required.
```

When I execute the command with nested folders (see the following directory structure), it leads to an error : 

- command : `sumecmd.exe -d .\UAL --csv out-ual`

- directory structure :
```
.\
└───UAL (folder)
    └───000100000001B553_0 (folder)
            Current.mdb
            SystemIdentity.mdb
            {8ED0B726-D0AB-401A-8EE9-B4467566629E}.mdb
            {C43924C8-8BCA-44CB-A9D7-EA3434F2DD6E}.mdb
```

- error : `File '.\UAL\SystemIdentity.mdb' not found!`

Reading the code shows that `Directory.GetFiles` is used, which does not seem to be recursive : 
https://github.com/EricZimmerman/Sum/blob/master/SumData/Sum.cs#L40

As a side note, in my use case, i may have several nested folders within UAL folder containing several mdb files, I don't know if SumECmd can handle several SystemIdentity.mdb files from different folders. I may have to execute one instance of sumecmd for each nested folder.

Thanks !

**Comment by EricZimmerman** [comment]
So the language in the description of the d switch is what's the problem here?

I'll remove the word recursively from the description

The tool was not designed to iterate and keep separate 15 different instances. So what you'll have to do is wrap it in a script that essentially pre-discovers the directories that contain the files are interested in

So your need to use .\ual\000100000001B553_0

In your example above

Most of my tools are recursive, but looking for link files that have no relationship to each other is different than this particular tool which expects several of those different database files in one place

**Comment by qlemaire** [comment]
Thanks for the quick answer!

> So the language in the description of the d switch is what's the problem here?

I think so

> The tool was not designed to iterate and keep separate 15 different instances. So what you'll have to do is wrap it in a script that essentially pre-discovers the directories that contain the files are interested in

Agreed, I went this way

**Comment by EricZimmerman** [comment]
yea i use the same switches, more or less, in all my apps and erroneously left in the 'recursive' mention for this one. will fix for next release
